## 启动顺序： #1

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

server:
  port: 20001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer2:20000/eureka
  instance:
    ## 将localhost指向本机（host文件）
    hostname: peer1