
spring:
  application:
    name: auth
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 20005
  address: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false




